# Exercises

### #1 - Calculate the BMI (body mass index) on the two lists below using NDArrays...

In [5]:
import numpy as np
#formula = weight / (height**2) * 730
height = [69, 70, 71, 72, 73, 74, 75]
weight = [110, 120, 130, 140, 150, 160, 170]

height_ND =np.array([69, 70, 71, 72, 73, 74, 75])
weight_ND =np.array( [110, 120, 130, 140, 150, 160, 170])

BMI= weight_ND/(height_ND**2)*730
print(BMI)


[16.86620458 17.87755102 18.82562984 19.71450617 20.54794521 21.32943755
 22.06222222]


### #2 - Create a function that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [23]:


random_x=np.random.uniform(0, 10,(3,4))

print(f"The matrix is:\n {random_x} \n The data type of random_x is: {random_x.dtype}")




The matrix is:
 [[7.14928466 8.38217311 2.79015644 8.59568064]
 [0.12878463 8.9335237  0.38886574 5.23400294]
 [2.60814641 6.9438071  1.07278007 5.61764912]] 
 The data type of random_x is: float64


### #3 - Extra: Open and load the data in the two text files that have the Boston Red Sox hitting data for the past seasons. Compare the difference in the two years by putting the data into an NDArray and running a differencial operation on it. The column to look for will be SLG.

Your output should display which year (either 2017 or 2018) was a better year based on SLG

In [1]:
import csv
import numpy as np




In [24]:
FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

#Use this function to actually open the data inside of a NDArray


def load(filename, d = ','):
    data = np.genfromtxt(filename,delimiter = d, skip_header = 1,
                        usecols = np.arange(0,24),invalid_raise=False,
                        names = FIELDS, dtype = DATATYPES)
    return data

bos2017 = load('redsox_2017_hitting.txt')
bos2018 = load('redsox_2018_hitting.txt')




arr17=np.array(bos2017['SLG'][0:20])
print(f'Boston Red Sox SLG in 2017: \n {arr17}')

arr18=np.array(bos2018['SLG'])
print(f'Boston Red Sox SLG in 2018: \n {arr18}')

diff= arr17-arr18
print(f'The SLG comparing the 2017 and 2018 is: \n {diff}') 





Boston Red Sox SLG in 2017: 
 [0.404 0.443 0.392 0.403 0.482 0.424 0.402 0.459 0.429 0.354 0.387 0.333
 0.539 0.243 0.262 0.354 0.342 0.339 0.328 0.306]
Boston Red Sox SLG in 2018: 
 [0.279 0.433 0.388 0.522 0.433 0.465 0.403 0.64  0.629 0.411 0.283 0.328
 0.395 0.507 0.311 0.415 0.389 0.261 0.091 0.167]
The SLG comparing the 2017 and 2018 is: 
 [ 0.125       0.00999999  0.00399998 -0.11900002  0.04899999 -0.04100001
 -0.00099999 -0.181      -0.20000002 -0.05700001  0.104       0.005
  0.14399996 -0.26400003 -0.04899999 -0.06099999 -0.04699999  0.07799998
  0.23700002  0.139     ]
